### ISSUE TITLE
Astar invalid injector error

### ISSUE THREAD

**Issue by cschaap** [AstarNetwork/astar-apps#681]
I have staked on the Astar Network and have collected rewards, but now I get an error message when I try.  I am relatively new to Astar & Polkadot ecosystems.  Possible causes for my problem:  I recently sent tokens from MetaMask to EVM deposit on Astar Network and I connected Talisman wallet to Polkadot and Astar?  Any help and advice?  Thanks

**Comment by bobo-k2** [comment]
Please share error details.

**Comment by cschaap** [comment]
https://portal.astar.network/#/astar/dapp-staking/discover:~:text=Error-,Invalid%20injector

Not sure what you are asking for?  Does this work?

**Comment by bobo-k2** [comment]
It doesn't help much. Can you write a precise steps how to reproduce the error, describe your environment (OS, browser, wallet etc...). Screenshots are also welcome.

Astar dApps staking works with Substrate accounts only (EVM accounts are not supported). In order to claim you rewards you need to connect to the Astar portal with the same account you used for staking.

**Comment by Kahonnohak** [comment]
Clear your cache or change the RPC. 99% will be sorted. I will close the issue.
